### ISSUE TITLE
[3장] 쿠버네티스에서 애플리케이션을 동작시키는 구조

### ISSUE THREAD

**Issue by creaton60** [BookStudyWithChimaek/2021-Season3#9]

**Comment by creaton60** [comment]
## 이 장에서 다루는 내용

* ### 컨테이너를 동작시키기 위한 리소스인 pod, replicaset, deployment, cronjob, job 의 동작
* ### 컨테이너를 외부에 공개하기 위한 서비스의 역할과 종류
* ### pod 를 graceful 하게 Deployment 하기 위한 Read / Live Probe 
* ### pod 라이프싸이클과 안전한 파드 정지를 위한 preStop 
* ### 파드가 확보한 로시스를 관리하는 Request & Limit 

## 이 이슈에서 얘기할 내용 
* pod 에 대한 개념, replicaset, deployment 
* 컨테이너를 외부에 공개하기 위한 서비스의 역할과 종류

**Comment by creaton60** [comment]
![KakaoTalk_Photo_2021-10-08-20-32-24](https://user-images.githubusercontent.com/4568248/136549720-8cb4af70-86e2-438e-a276-1a8216dc5504.jpeg)

**Comment by creaton60** [comment]
## Pod 란?
* 서로 관련성이 있는 하나 이상의 컨테이너를 합쳐놓은 오브젝트 

Pod manifest file example 
```yaml 
apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels: 
        app: nginx-app
spec:
   containers:
    - name: nginx-container
       images: nginx
       ports:
        - containerPort: 80
```

* apiVersion
* kind
* name
* app
* spec
  * containers : 여러개의 컨테이너를 설정할 수 있음.

![KakaoTalk_Photo_2021-10-08-20-42-38](https://user-images.githubusercontent.com/4568248/136551004-04b68c10-1642-4179-a3f4-635b874fa9b7.jpeg)

**Comment by creaton60** [comment]
### 파드 초기화 컨테이너
* 파드의 메인 컨테이너를 생성하기 전에 초기화 컨테이너 실행하도록 설정 가능
  * 애플리케이션 자체에 필요 없는 도구를 사용하여 초기화 처리 가능

**Comment by creaton60** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kubectl
  name: gateway-env-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: gateway
        tags.datadoghq.com/version: 1.0.0
        app: gateway-prod
    spec:
      containers:
        - env:
          image: DOCKER_IMAGE_PLACE_HOLDER:DOCKER_IMAGE_TAG_PLACEHOLDER
          imagePullPolicy: Always

```

**Comment by creaton60** [comment]
```yaml
ports:
       - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 2000m
              memory: 4096Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
```

**Comment by creaton60** [comment]
```yaml
lifecycle:
   preStop:
       exec:
          command: ["/bin/sh", "-c", "sleep 2"]
```
